### ISSUE TITLE
`<h4>` inside `<p>`?

### ISSUE THREAD

**Issue by benhcv** [lanaleyla/CodeValueEXE#3]
Did you use do that on purpose? What was the objective?

**Comment by lanaleyla** [comment]
yes it was on purpose, i wanted to define the size of the text in the paragraph , because we did not use css i thought it would use h4 to controll the size.

**Comment by benhcv** [comment]
OK, the <h4> would give you that default styling. Why did you need the outer <p>? Once you start using CSS for styling, you should avoid defining style in HTML.

**Comment by lanaleyla** [comment]
I needed the outer<p> because i wanted it to be semanticly correct, it was
a description of the product and i thought it should be inside of a
paragraph.
I used it again , in the second exercise inside of a section , but it was a
mistake, i could use the h3 tag id attribute instead. I will pay more
attention to that.
Thank you.

בתאריך יום ד׳, 19 ביוני 2019, 12:59, מאת Ben Hornedo ‏<
notifications@github.com>:
